In [ ]:
from sklearn.model_selection import train_test_split

def load_one_file(filename):
    with open(filename, encoding='utf8') as f:
        return [str(i.strip()) for i in f.readlines()]  # 确保每一行都被转换为字符串

def load_all_files():
    x_train = []
    y_train = []
    x_test = []
    y_test = []

    dataNum = 200

    # Load and label the data
    x_normal = load_one_file('data/normal.txt')[:200]
    y_normal = [0] * dataNum 

    x_weak = load_one_file('data/weak.txt')[:200]
    y_weak = [1] * dataNum 

    x_token = load_one_file('data/tokens.txt')[:200]
    y_token = [2] * dataNum

    # Combine all data
    x = x_normal + x_weak + x_token
    y = y_normal + y_weak + y_token

    # Split the data into training and test sets
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

    return x_train, y_train, x_test, y_test

x_train, y_train, x_test, y_test = load_all_files()
print(f"Training data size: {len(x_train)}")
print(f"Test data size: {len(x_test)}")

Training data size: 480
Test data size: 120


In [8]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'x_train':x_train, 
              'y_train':y_train,
              'x_test':x_test+['']*int(len(x_train)-len(x_test)),
              'y_test':y_test+[0]*int(len(x_train)-len(x_test)) })

In [10]:
df

x_train  y_train  \
0                                                  any        0   
1                                               other.        0   
2                                              d-money        1   
3    wzws_sessionid=gjVmZGQ3ZIE1ZjBmZjWAMTM5LjIwNS4...        2   
4                                               firing        0   
..                                                 ...      ...   
475                                       conventional        0   
476                                             albeit        0   
477                                           03050404        1   
478            userid=9966d14e24594fa88a52145e999567ee        2   
479                                              then,        0   

                                                x_test  y_test  
0                                               placed       0  
1    wzws_sessionid=gDIxOS4xNDQuMjE4LjE5OYFmYjVhZTS...       2  
2          JSESSIONID=B519EA2C2FD0F3BF95278D031C312CD7       2  
3                                               begins       0  
4                                               verges       0  
..                                                 ...     ...  
475                                                          0  
476                                                          0  
477                                                          0  
478                                                          0  
479                                                          0  

[480 rows x 4 columns]

In [12]:
for i in x_test:
    if type(i) != str:
        print(i, type(i))
        break

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
max_features=500

vectorizer = CountVectorizer(
                                decode_error='ignore',
                                strip_accents='ascii',
                                max_features=max_features,
                                max_df=1.0,
                                min_df=1 )
print(vectorizer)
x_train=vectorizer.fit_transform(x_train)
x_train=x_train.toarray()

CountVectorizer(decode_error='ignore', max_features=500, strip_accents='ascii')


In [15]:
vocabulary=vectorizer.vocabulary_
# 复用vocabulary对测试数据集进行词袋化处理
vectorizer = CountVectorizer(
                                decode_error='ignore',
                                strip_accents='ascii',
                                vocabulary=vocabulary,
                                max_df=1.0,
                                min_df=1 )
print(vectorizer)
x_test=vectorizer.fit_transform(x_test)
x_test=x_test.toarray()

CountVectorizer(decode_error='ignore', strip_accents='ascii',
                vocabulary={'00270a40': 0, '010492': 1, '01382338': 2,
                            '01bde269f84d434ca20220cff0302dda': 3,
                            '01ecb811': 4, '02081983': 5, '021f2a73d5af': 6,
                            '03050404': 7, '030587': 8, '040585': 9,
                            '040889': 10, '06071987': 11, '06d3': 12,
                            '090587': 13, '0c74dd175df74c63': 14,
                            '0dc6d096': 15, '0e2a0fe706cc': 16,
                            '0yo8prbrxk22yjh': 17, '10121983': 18, '101983': 19,
                            '10a07a9ab7e6': 20, '11091979': 21,
                            '11eedf4acaed': 22, '11k2': 23, '123456gg': 24,
                            '123qwe': 25, '12451245': 26, '1262715109': 27,
                            '1379': 28, '147258a': 29, ...})


In [ ]:
df = pd.DataFrame(x_train) # 每一行代表一个文档，每一列代表一个词汇，矩阵中的值表示词汇在文档中出现的次数。
df

0    1    2    3    4    5    6    7    8    9    ...  490  491  492  \
0      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4      0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
475    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
476    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
477    0    0    0    0    0    0    0    1    0    0  ...    0    0    0   
478    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
479    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   

     493  494  495  496  497  498  499  
0      0    0    0    0    0    0    0  
1      0    0    0    0    0    0    0  
2      0    0    0    0    0    0    0  
3      0    0    0    0    0    0    0  
4      0    0    0    0    0    0    0  
..   ...  ...  ...  ...  ...  ...  ...  
475    0    0    0    0    0    0    0  
476    0    0    0    0    0    0    0  
477    0    0    0    0    0    0    0  
478    0    0    0    0    0    0    0  
479    0    0    0    0    0    0    0  

[480 rows x 500 columns]

In [24]:
from sklearn.linear_model import LogisticRegression

# Initialize the classifier
classifier = LogisticRegression(max_iter=1000)

# Train the classifier
classifier.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [25]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Predict the labels for the test set
y_pred = classifier.predict(x_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Print confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Print classification report
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Accuracy: 0.58
Confusion Matrix:
[[ 2 41  0]
 [ 0 36  0]
 [ 0  9 32]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.05      0.09        43
           1       0.42      1.00      0.59        36
           2       1.00      0.78      0.88        41

    accuracy                           0.58       120
   macro avg       0.81      0.61      0.52       120
weighted avg       0.83      0.58      0.51       120



In [26]:
import joblib

# 保存模型和向量化器
joblib.dump(classifier, 'logistic_regression_model.pkl')
joblib.dump(vectorizer, 'count_vectorizer.pkl')

['count_vectorizer.pkl']

In [5]:
from unittest import result
import joblib

def load_model_and_vectorizer(model_path, vectorizer_path):
    """
    加载训练好的模型和向量化器
    """
    model = joblib.load(model_path)
    vectorizer = joblib.load(vectorizer_path)
    return model, vectorizer

def predict_text(text, model, vectorizer):
    """
    使用加载的模型和向量化器对输入文本进行预测
    """
    # 将输入文本转换为特征向量
    text_counts = vectorizer.transform([text])
    
    # 进行预测
    prediction = model.predict(text_counts)
    
    return prediction[0]

# 加载模型和向量化器
model, vectorizer = load_model_and_vectorizer('logistic_regression_model.pkl', 'count_vectorizer.pkl')

# 示例预测
input_text = "1"
prediction = predict_text(input_text, model, vectorizer)

result = ['normal/正常', 'weak/弱口令', 'tokens/令牌']
print(f"预测出来的结果是: {result[prediction]}")

预测出来的结果是: weak/弱口令
